[notebook]
dir = "/mnt/notes/"

[extra]
author = "Vincent"

[tool]
editor = "nvim"
fzf-preview = "bat -p --color=always {-1}"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
